---
title: "FiveThirtyEight Bechdel Data"
author: Anna Henschel
output: 
  github_document:
    fig_width: 10
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bechdel data

Inspired by the following vignette by Chester Ismay: https://fivethirtyeight-r.netlify.com/articles/bechdel.html.  

Load libraries
```{r, message=FALSE, warning=FALSE}
library(fivethirtyeight) # Bechdel data from fivethirtyeight 
library(ggsci) # color palettes with a lot of flexibility
library(ggthemes) # pretty ggplot themes
library(janitor) # aggregate frequencies of factors
library(knitr) # make nice tables
library(reshape2)
library(tidyverse) # tidy data wrangling

# Turn off scientific notation
options(scipen = 99)
```

Load data
```{r}
data(bechdel) # get data included in the fivethirtyeight package
glimpse(bechdel)
```

How many movies pass and fail overall vs. over time?
```{r}
# Find out the overall percentage
perc_bechdel <- bechdel %>%
  filter(between(year, 1990, 2013)) %>%
  tabyl(binary)

kable(perc_bechdel)

# See how this develops over years:
perc_bechdel_time <- bechdel %>%
  filter(between(year, 1990, 2013)) %>%
  tabyl(year, binary) %>%
  reshape::melt(id="year")
```

A small majority of movies fails the bechdel test:
```{r}
perc_bechdel %>%
  ggplot(aes(x = binary, y = percent, fill = binary)) + 
  geom_bar(stat = "identity") + 
  scale_y_continuous(labels=scales::percent, limits = c(0,.7), breaks = c(0, .1, .2, .3, .4, .5, .6)) +
  coord_flip() +
  theme_fivethirtyeight() +
  scale_fill_d3() +
  theme(legend.position = "none", 
        axis.text.x = element_text(size =14), 
        axis.text.y = element_text(size =14)) +
  labs(x = '', y = '',
         title = 'Proportion of movies between 1990 and 2013 passing the Bechdel Test', 
       subtitle = 'The test asks whether a work features at least two women who talk to each other about something other than a man.',
         caption = 'Data by FiveThirtyEight\n #BechdelTest • @AnnaHenschel') 
```


```{r}
# Find out what the top international grossing movie is in each of the Bechdel Test categories
bechdel %>%
  filter(between(year, 1990, 2013)) %>%
  filter(clean_test == "ok") %>%
  select(title, binary, clean_test, intgross) %>%
  arrange(desc(intgross))

# Find a way to do this withot manually changing the filter!
```

How does this split up in different categories?
```{r}
bechdel %>%
  filter(between(year, 1990, 2013)) %>%
  ggplot(aes(x = clean_test, fill = clean_test)) + 
  geom_bar() + 
  ylim(0,850) +
  annotate("text", x = "nowomen", y = 220, label = "For example:\n The Hobbit:\n An Unexpected Journey", alpha = .65) +
    annotate("text", x = "notalk", y = 580, label = "For example:\n Harry Potter and\n the Deathly Hallows:\n Part 2", alpha = .65) +
    annotate("text", x = "men", y = 250, label = "For example:\n Avatar", alpha = .65) +
    annotate("text", x = "dubious", y = 200, label = "For example:\n Iron Man 3", alpha = .65) +
    annotate("text", x = "ok", y = 830, label = "For example:\n Titanic", alpha = .65) +
  theme_fivethirtyeight() +
  scale_fill_d3() +
  scale_x_discrete(labels=c("nowomen" = "Less than\n 2 women", "notalk" = "At least 2 women,\n who don't talk\n to each other","men" = "At least 2 women,\n talking about men", "dubious" = "Dubious", "ok" ="At least 2 women\n who are talking to each other\n about something else\n than men")) +
  theme(legend.position = "none", 
        axis.text.x = element_text(size =14), 
        axis.text.y = element_text(size =14)) +
  labs(x = '', y = '',
         title = 'Movies between 1990 and 2013 by Bechdel Test category', 
       subtitle = 'The test asks whether a work features at least two women who talk to each other about something other than a man.\nFor each category, an example of the highest international grossing movie is given.',
         caption = 'Data by FiveThirtyEight\n #BechdelTest • @AnnaHenschel')
```


Does this change over time?
```{r}
ggplot(perc_bechdel_time,
       aes(x = year, y = value, colour = variable)) +
       geom_line(size = 3) +
  theme_fivethirtyeight() +
  scale_colour_d3() +
  theme(legend.position = "none", 
        axis.text.x = element_text(size =16), 
        axis.text.y = element_text(size =16)) +
  labs(x = '', y = '',
         title = 'Movies passing and failing the Bechdel test over time', 
       subtitle = 'The test asks whether a work features at least two women who talk to each other about something other than a man.',
         caption = 'Data by FiveThirtyEight\n #BechdelTest • @AnnaHenschel') 
```
